"""initial_schema

Revision ID: 202607150001
Revises:
Create Date: 2026-07-15 18:30:05.647951
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "202607150001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appuser",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email_normalized", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(), nullable=True),
        sa.Column("password_changed_at", sa.DateTime(), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email_normalized", name="ux_appuser_email_normalized"),
    )
    op.create_index(op.f("ix_appuser_created_at"), "appuser", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_appuser_email_normalized"), "appuser", ["email_normalized"], unique=False
    )
    op.create_index(
        op.f("ix_appuser_email_verified_at"), "appuser", ["email_verified_at"], unique=False
    )
    op.create_index(op.f("ix_appuser_last_login_at"), "appuser", ["last_login_at"], unique=False)
    op.create_index(op.f("ix_appuser_locked_until"), "appuser", ["locked_until"], unique=False)
    op.create_index(op.f("ix_appuser_role"), "appuser", ["role"], unique=False)
    op.create_index("ix_appuser_role_status", "appuser", ["role", "status"], unique=False)
    op.create_index(op.f("ix_appuser_status"), "appuser", ["status"], unique=False)
    op.create_table(
        "adminauditlog",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("actor_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("request_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["appuser.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["appuser.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_adminauditlog_action"), "adminauditlog", ["action"], unique=False)
    op.create_index(
        "ix_adminauditlog_actor_created",
        "adminauditlog",
        ["actor_user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_adminauditlog_actor_user_id"), "adminauditlog", ["actor_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_adminauditlog_created_at"), "adminauditlog", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_adminauditlog_request_id"), "adminauditlog", ["request_id"], unique=False
    )
    op.create_index(
        "ix_adminauditlog_target_created",
        "adminauditlog",
        ["target_user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_adminauditlog_target_user_id"), "adminauditlog", ["target_user_id"], unique=False
    )
    op.create_table(
        "agentprofile",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["appuser.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="ux_agentprofile_user_name"),
    )
    op.create_index(op.f("ix_agentprofile_name"), "agentprofile", ["name"], unique=False)
    op.create_index(op.f("ix_agentprofile_user_id"), "agentprofile", ["user_id"], unique=False)
    op.create_index(
        "ix_agentprofile_user_updated", "agentprofile", ["user_id", "updated_at"], unique=False
    )
    op.create_table(
        "authsession",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("csrf_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ip_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["appuser.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash", name="ux_authsession_token_hash"),
    )
    op.create_index(op.f("ix_authsession_expires_at"), "authsession", ["expires_at"], unique=False)
    op.create_index(op.f("ix_authsession_revoked_at"), "authsession", ["revoked_at"], unique=False)
    op.create_index(op.f("ix_authsession_token_hash"), "authsession", ["token_hash"], unique=False)
    op.create_index(
        "ix_authsession_user_active",
        "authsession",
        ["user_id", "revoked_at", "expires_at"],
        unique=False,
    )
    op.create_index(op.f("ix_authsession_user_id"), "authsession", ["user_id"], unique=False)
    op.create_table(
        "modelusage",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("call_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("execution_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("usage_available", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["appuser.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("call_id", name="ux_modelusage_call_id"),
    )
    op.create_index(op.f("ix_modelusage_call_id"), "modelusage", ["call_id"], unique=False)
    op.create_index(op.f("ix_modelusage_category"), "modelusage", ["category"], unique=False)
    op.create_index(op.f("ix_modelusage_created_at"), "modelusage", ["created_at"], unique=False)
    op.create_index(
        "ix_modelusage_execution_category", "modelusage", ["execution_id", "category"], unique=False
    )
    op.create_index(
        op.f("ix_modelusage_execution_id"), "modelusage", ["execution_id"], unique=False
    )
    op.create_index(op.f("ix_modelusage_latency_ms"), "modelusage", ["latency_ms"], unique=False)
    op.create_index(op.f("ix_modelusage_model_name"), "modelusage", ["model_name"], unique=False)
    op.create_index(op.f("ix_modelusage_provider"), "modelusage", ["provider"], unique=False)
    op.create_index(op.f("ix_modelusage_session_id"), "modelusage", ["session_id"], unique=False)
    op.create_index(op.f("ix_modelusage_status"), "modelusage", ["status"], unique=False)
    op.create_index(
        op.f("ix_modelusage_usage_available"), "modelusage", ["usage_available"], unique=False
    )
    op.create_index(
        "ix_modelusage_user_created", "modelusage", ["user_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_modelusage_user_id"), "modelusage", ["user_id"], unique=False)
    op.create_table(
        "useractiontoken",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("purpose", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["appuser.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash", name="ux_useractiontoken_token_hash"),
    )
    op.create_index(
        op.f("ix_useractiontoken_expires_at"), "useractiontoken", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_useractiontoken_purpose"), "useractiontoken", ["purpose"], unique=False
    )
    op.create_index(
        op.f("ix_useractiontoken_token_hash"), "useractiontoken", ["token_hash"], unique=False
    )
    op.create_index(
        op.f("ix_useractiontoken_used_at"), "useractiontoken", ["used_at"], unique=False
    )
    op.create_index(
        op.f("ix_useractiontoken_user_id"), "useractiontoken", ["user_id"], unique=False
    )
    op.create_index(
        "ix_useractiontoken_user_purpose",
        "useractiontoken",
        ["user_id", "purpose", "created_at"],
        unique=False,
    )
    op.create_table(
        "agentversion",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("topic_scoring_prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hotspot_sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agentprofile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "version", name="ux_agentversion_agent_version"),
    )
    op.create_index(
        "ix_agentversion_agent_created", "agentversion", ["agent_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_agentversion_agent_id"), "agentversion", ["agent_id"], unique=False)
    op.create_index(op.f("ix_agentversion_version"), "agentversion", ["version"], unique=False)
    op.create_table(
        "chatsession",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_version_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("langgraph_thread_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agentprofile.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["agent_version_id"], ["agentversion.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["appuser.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chatsession_agent_id"), "chatsession", ["agent_id"], unique=False)
    op.create_index(
        "ix_chatsession_agent_updated", "chatsession", ["agent_id", "updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_chatsession_agent_version_id"), "chatsession", ["agent_version_id"], unique=False
    )
    op.create_index(
        op.f("ix_chatsession_langgraph_thread_id"),
        "chatsession",
        ["langgraph_thread_id"],
        unique=True,
    )
    op.create_index(op.f("ix_chatsession_user_id"), "chatsession", ["user_id"], unique=False)
    op.create_index(
        "ix_chatsession_user_updated", "chatsession", ["user_id", "updated_at"], unique=False
    )
    op.create_table(
        "agentinvocation",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("idempotency_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agentprofile.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["session_id"], ["chatsession.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["appuser.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id", "idempotency_key", name="ux_agentinvocation_session_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_agentinvocation_agent_id"), "agentinvocation", ["agent_id"], unique=False
    )
    op.create_index(
        "ix_agentinvocation_session_created",
        "agentinvocation",
        ["session_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agentinvocation_session_id"), "agentinvocation", ["session_id"], unique=False
    )
    op.create_index(
        "ix_agentinvocation_user_created",
        "agentinvocation",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agentinvocation_user_id"), "agentinvocation", ["user_id"], unique=False
    )
    op.create_table(
        "memoryrecord",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("memory_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "semantic",
                "episodic",
                "procedural",
                "summary",
                "profile",
                "preference",
                "goal",
                name="memorykind",
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("importance_score", sa.Float(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "manual",
                "user_message",
                "turn_summary",
                "summary",
                "tool",
                "system",
                name="memorysourcetype",
            ),
            nullable=False,
        ),
        sa.Column("source_session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_message_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_execution_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("access_count", sa.Integer(), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(agent_id IS NOT NULL AND session_id IS NULL) OR (agent_id IS NULL AND session_id IS NOT NULL)",
            name="ck_memoryrecord_owner",
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agentprofile.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["chatsession.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["appuser.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_memoryrecord_agent_id"), "memoryrecord", ["agent_id"], unique=False)
    op.create_index(
        op.f("ix_memoryrecord_deleted_at"), "memoryrecord", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_memoryrecord_expires_at"), "memoryrecord", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_memoryrecord_kind"), "memoryrecord", ["kind"], unique=False)
    op.create_index(
        op.f("ix_memoryrecord_last_accessed_at"), "memoryrecord", ["last_accessed_at"], unique=False
    )
    op.create_index(
        "ix_memoryrecord_lookup",
        "memoryrecord",
        ["user_id", "agent_id", "session_id", "kind", "updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memoryrecord_memory_key"), "memoryrecord", ["memory_key"], unique=False
    )
    op.create_index(
        op.f("ix_memoryrecord_session_id"), "memoryrecord", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_memoryrecord_source_execution_id"),
        "memoryrecord",
        ["source_execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memoryrecord_source_message_id"),
        "memoryrecord",
        ["source_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memoryrecord_source_session_id"),
        "memoryrecord",
        ["source_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memoryrecord_source_type"), "memoryrecord", ["source_type"], unique=False
    )
    op.create_index(op.f("ix_memoryrecord_user_id"), "memoryrecord", ["user_id"], unique=False)
    op.create_index(
        "ux_memoryrecord_active_agent",
        "memoryrecord",
        ["user_id", "agent_id", "memory_key"],
        unique=True,
        postgresql_where=sa.text("agent_id IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_index(
        "ux_memoryrecord_active_session",
        "memoryrecord",
        ["user_id", "session_id", "memory_key"],
        unique=True,
        postgresql_where=sa.text("session_id IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_table(
        "agentexecution",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("invocation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_version_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("trace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("latest_checkpoint_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "waiting_input",
                "completed",
                "failed",
                "cancelled",
                name="runstatus",
            ),
            nullable=False,
        ),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("interrupt_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resume_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("cancel_requested_at", sa.DateTime(), nullable=True),
        sa.Column("claimed_at", sa.DateTime(), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(), nullable=True),
        sa.Column("worker_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column(
            "next_attempt_kind",
            sa.Enum("initial", "resume", "retry", name="executionattemptkind"),
            nullable=False,
        ),
        sa.Column("current_attempt_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("first_event_at", sa.DateTime(), nullable=True),
        sa.Column("first_token_at", sa.DateTime(), nullable=True),
        sa.Column("streaming_degraded", sa.Boolean(), nullable=False),
        sa.Column("streaming_degraded_at", sa.DateTime(), nullable=True),
        sa.Column("streaming_degraded_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("postprocess_completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["agent_version_id"], ["agentversion.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["invocation_id"], ["agentinvocation.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agentexecution_agent_version_id"),
        "agentexecution",
        ["agent_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agentexecution_cancel_requested_at"),
        "agentexecution",
        ["cancel_requested_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agentexecution_claimed_at"), "agentexecution", ["claimed_at"], unique=False
    )
    op.create_index(
        op.f("ix_agentexecution_current_attempt_id"),
        "agentexecution",
        ["current_attempt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agentexecution_first_event_at"), "agentexecution", ["first_event_at"], unique=False
    )
    op.create_index(
        op.f("ix_agentexecution_first_token_at"), "agentexecution", ["first_token_at"], unique=False
    )
    op.create_index(
        op.f("ix_agentexecution_heartbeat_at"), "agentexecution", ["heartbeat_at"], unique=False
    )
    op.create_index(
        "ix_agentexecution_invocation_created",
        "agentexecution",
        ["invocation_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agentexecution_invocation_id"), "agentexecution", ["invocation_id"], unique=False
    )
    op.create_index(
        "ix_agentexecution_invocation_status",
        "agentexecution",
        ["invocation_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agentexecution_latest_checkpoint_id"),
        "agentexecution",
        ["latest_checkpoint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agentexecution_lease_expires_at"),
        "agentexecution",
        ["lease_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agentexecution_next_attempt_kind"),
        "agentexecution",
        ["next_attempt_kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agentexecution_postprocess_completed_at"),
        "agentexecution",
        ["postprocess_completed_at"],
        unique=False,
    )
    op.create_index(op.f("ix_agentexecution_status"), "agentexecution", ["status"], unique=False)
    op.create_index(
        "ix_agentexecution_status_updated", "agentexecution", ["status", "updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_agentexecution_streaming_degraded"),
        "agentexecution",
        ["streaming_degraded"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agentexecution_streaming_degraded_at"),
        "agentexecution",
        ["streaming_degraded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agentexecution_trace_id"), "agentexecution", ["trace_id"], unique=False
    )
    op.create_index(
        op.f("ix_agentexecution_worker_id"), "agentexecution", ["worker_id"], unique=False
    )
    op.create_table(
        "chatmessage",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("invocation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("role", sa.Enum("user", "assistant", name="messagerole"), nullable=False),
        sa.Column("message_type", sa.Enum("text", "markdown", name="messagetype"), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["invocation_id"], ["agentinvocation.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["chatsession.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chatmessage_invocation_id"), "chatmessage", ["invocation_id"], unique=False
    )
    op.create_index(
        "ix_chatmessage_session_created_id",
        "chatmessage",
        ["session_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(op.f("ix_chatmessage_session_id"), "chatmessage", ["session_id"], unique=False)
    op.create_table(
        "agentexecutionattempt",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("execution_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("initial", "resume", "retry", name="executionattemptkind"),
            nullable=False,
        ),
        sa.Column("worker_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "waiting_input",
                "completed",
                "failed",
                "cancelled",
                "lease_lost",
                name="executionattemptstatus",
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("first_event_at", sa.DateTime(), nullable=True),
        sa.Column("first_token_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["execution_id"], ["agentexecution.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "execution_id", "ordinal", name="ux_agentexecutionattempt_execution_ordinal"
        ),
    )
    op.create_index(
        op.f("ix_agentexecutionattempt_execution_id"),
        "agentexecutionattempt",
        ["execution_id"],
        unique=False,
    )
    op.create_index(
        "ix_agentexecutionattempt_execution_started",
        "agentexecutionattempt",
        ["execution_id", "started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agentexecutionattempt_kind"), "agentexecutionattempt", ["kind"], unique=False
    )
    op.create_index(
        op.f("ix_agentexecutionattempt_ordinal"), "agentexecutionattempt", ["ordinal"], unique=False
    )
    op.create_index(
        op.f("ix_agentexecutionattempt_status"), "agentexecutionattempt", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_agentexecutionattempt_worker_id"),
        "agentexecutionattempt",
        ["worker_id"],
        unique=False,
    )
    op.create_table(
        "executionoutbox",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("execution_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("request_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("processing_attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(), nullable=False),
        sa.Column("locked_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["execution_id"], ["agentexecution.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("execution_id", "kind", name="ux_executionoutbox_execution_kind"),
    )
    op.create_index(
        op.f("ix_executionoutbox_available_at"), "executionoutbox", ["available_at"], unique=False
    )
    op.create_index(
        op.f("ix_executionoutbox_execution_id"), "executionoutbox", ["execution_id"], unique=False
    )
    op.create_index(op.f("ix_executionoutbox_kind"), "executionoutbox", ["kind"], unique=False)
    op.create_index(
        op.f("ix_executionoutbox_locked_by"), "executionoutbox", ["locked_by"], unique=False
    )
    op.create_index(
        "ix_executionoutbox_locked_until", "executionoutbox", ["locked_until"], unique=False
    )
    op.create_index(
        op.f("ix_executionoutbox_published_at"), "executionoutbox", ["published_at"], unique=False
    )
    op.create_index(
        op.f("ix_executionoutbox_request_id"), "executionoutbox", ["request_id"], unique=False
    )
    op.create_index(op.f("ix_executionoutbox_status"), "executionoutbox", ["status"], unique=False)
    op.create_index(
        "ix_executionoutbox_status_available",
        "executionoutbox",
        ["status", "available_at"],
        unique=False,
    )
    op.create_table(
        "executionresumerequest",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("execution_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("interrupt_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tool_calls_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("claimed_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("claimed_at", sa.DateTime(), nullable=True),
        sa.Column("consumed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["execution_id"], ["agentexecution.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "execution_id", "interrupt_id", name="ux_executionresumerequest_execution_interrupt"
        ),
    )
    op.create_index(
        op.f("ix_executionresumerequest_claimed_at"),
        "executionresumerequest",
        ["claimed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_executionresumerequest_claimed_by"),
        "executionresumerequest",
        ["claimed_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_executionresumerequest_consumed_at"),
        "executionresumerequest",
        ["consumed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_executionresumerequest_execution_id"),
        "executionresumerequest",
        ["execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_executionresumerequest_interrupt_id"),
        "executionresumerequest",
        ["interrupt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_executionresumerequest_status"), "executionresumerequest", ["status"], unique=False
    )
    op.create_index(
        "ix_executionresumerequest_status_created",
        "executionresumerequest",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_executionresumerequest_tool_calls_hash"),
        "executionresumerequest",
        ["tool_calls_hash"],
        unique=False,
    )
    op.create_table(
        "researchpackage",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("execution_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_version_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("topic", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("topic_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("package_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provider_diagnostics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rendered_content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("valid_source_count", sa.Integer(), nullable=False),
        sa.Column("isolated_source_count", sa.Integer(), nullable=False),
        sa.Column("removed_unknown_reference_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_version_id"],
            ["agentversion.id"],
        ),
        sa.ForeignKeyConstraint(["execution_id"], ["agentexecution.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["chatsession.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "execution_id", "topic_hash", name="ux_researchpackage_execution_topic"
        ),
    )
    op.create_index(
        op.f("ix_researchpackage_agent_version_id"),
        "researchpackage",
        ["agent_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_researchpackage_execution_id"), "researchpackage", ["execution_id"], unique=False
    )
    op.create_index(
        "ix_researchpackage_session_created",
        "researchpackage",
        ["session_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_researchpackage_session_id"), "researchpackage", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_researchpackage_topic_hash"), "researchpackage", ["topic_hash"], unique=False
    )
    op.create_table(
        "toolexecution",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("execution_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tool_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tool_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tool_call_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("arguments_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("result_digest", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "completed", "failed", name="toolexecutionstatus"),
            nullable=False,
        ),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["execution_id"], ["agentexecution.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "execution_id", "tool_call_id", name="ux_toolexecution_execution_tool_call"
        ),
    )
    op.create_index(
        op.f("ix_toolexecution_arguments_hash"), "toolexecution", ["arguments_hash"], unique=False
    )
    op.create_index(
        op.f("ix_toolexecution_duration_ms"), "toolexecution", ["duration_ms"], unique=False
    )
    op.create_index(
        "ix_toolexecution_execution_created",
        "toolexecution",
        ["execution_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_toolexecution_execution_id"), "toolexecution", ["execution_id"], unique=False
    )
    op.create_index(
        "ix_toolexecution_execution_sequence",
        "toolexecution",
        ["execution_id", "sequence"],
        unique=False,
    )
    op.create_index(
        op.f("ix_toolexecution_result_digest"), "toolexecution", ["result_digest"], unique=False
    )
    op.create_index(op.f("ix_toolexecution_sequence"), "toolexecution", ["sequence"], unique=False)
    op.create_index(op.f("ix_toolexecution_status"), "toolexecution", ["status"], unique=False)
    op.create_index(
        op.f("ix_toolexecution_tool_call_id"), "toolexecution", ["tool_call_id"], unique=False
    )
    op.create_index(
        "ix_toolexecution_tool_created", "toolexecution", ["tool_name", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_toolexecution_tool_name"), "toolexecution", ["tool_name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_toolexecution_tool_name"), table_name="toolexecution")
    op.drop_index("ix_toolexecution_tool_created", table_name="toolexecution")
    op.drop_index(op.f("ix_toolexecution_tool_call_id"), table_name="toolexecution")
    op.drop_index(op.f("ix_toolexecution_status"), table_name="toolexecution")
    op.drop_index(op.f("ix_toolexecution_sequence"), table_name="toolexecution")
    op.drop_index(op.f("ix_toolexecution_result_digest"), table_name="toolexecution")
    op.drop_index("ix_toolexecution_execution_sequence", table_name="toolexecution")
    op.drop_index(op.f("ix_toolexecution_execution_id"), table_name="toolexecution")
    op.drop_index("ix_toolexecution_execution_created", table_name="toolexecution")
    op.drop_index(op.f("ix_toolexecution_duration_ms"), table_name="toolexecution")
    op.drop_index(op.f("ix_toolexecution_arguments_hash"), table_name="toolexecution")
    op.drop_table("toolexecution")
    op.drop_index(op.f("ix_researchpackage_topic_hash"), table_name="researchpackage")
    op.drop_index(op.f("ix_researchpackage_session_id"), table_name="researchpackage")
    op.drop_index("ix_researchpackage_session_created", table_name="researchpackage")
    op.drop_index(op.f("ix_researchpackage_execution_id"), table_name="researchpackage")
    op.drop_index(op.f("ix_researchpackage_agent_version_id"), table_name="researchpackage")
    op.drop_table("researchpackage")
    op.drop_index(
        op.f("ix_executionresumerequest_tool_calls_hash"), table_name="executionresumerequest"
    )
    op.drop_index("ix_executionresumerequest_status_created", table_name="executionresumerequest")
    op.drop_index(op.f("ix_executionresumerequest_status"), table_name="executionresumerequest")
    op.drop_index(
        op.f("ix_executionresumerequest_interrupt_id"), table_name="executionresumerequest"
    )
    op.drop_index(
        op.f("ix_executionresumerequest_execution_id"), table_name="executionresumerequest"
    )
    op.drop_index(
        op.f("ix_executionresumerequest_consumed_at"), table_name="executionresumerequest"
    )
    op.drop_index(op.f("ix_executionresumerequest_claimed_by"), table_name="executionresumerequest")
    op.drop_index(op.f("ix_executionresumerequest_claimed_at"), table_name="executionresumerequest")
    op.drop_table("executionresumerequest")
    op.drop_index("ix_executionoutbox_status_available", table_name="executionoutbox")
    op.drop_index(op.f("ix_executionoutbox_status"), table_name="executionoutbox")
    op.drop_index(op.f("ix_executionoutbox_request_id"), table_name="executionoutbox")
    op.drop_index(op.f("ix_executionoutbox_published_at"), table_name="executionoutbox")
    op.drop_index("ix_executionoutbox_locked_until", table_name="executionoutbox")
    op.drop_index(op.f("ix_executionoutbox_locked_by"), table_name="executionoutbox")
    op.drop_index(op.f("ix_executionoutbox_kind"), table_name="executionoutbox")
    op.drop_index(op.f("ix_executionoutbox_execution_id"), table_name="executionoutbox")
    op.drop_index(op.f("ix_executionoutbox_available_at"), table_name="executionoutbox")
    op.drop_table("executionoutbox")
    op.drop_index(op.f("ix_agentexecutionattempt_worker_id"), table_name="agentexecutionattempt")
    op.drop_index(op.f("ix_agentexecutionattempt_status"), table_name="agentexecutionattempt")
    op.drop_index(op.f("ix_agentexecutionattempt_ordinal"), table_name="agentexecutionattempt")
    op.drop_index(op.f("ix_agentexecutionattempt_kind"), table_name="agentexecutionattempt")
    op.drop_index("ix_agentexecutionattempt_execution_started", table_name="agentexecutionattempt")
    op.drop_index(op.f("ix_agentexecutionattempt_execution_id"), table_name="agentexecutionattempt")
    op.drop_table("agentexecutionattempt")
    op.drop_index(op.f("ix_chatmessage_session_id"), table_name="chatmessage")
    op.drop_index("ix_chatmessage_session_created_id", table_name="chatmessage")
    op.drop_index(op.f("ix_chatmessage_invocation_id"), table_name="chatmessage")
    op.drop_table("chatmessage")
    op.drop_index(op.f("ix_agentexecution_worker_id"), table_name="agentexecution")
    op.drop_index(op.f("ix_agentexecution_trace_id"), table_name="agentexecution")
    op.drop_index(op.f("ix_agentexecution_streaming_degraded_at"), table_name="agentexecution")
    op.drop_index(op.f("ix_agentexecution_streaming_degraded"), table_name="agentexecution")
    op.drop_index("ix_agentexecution_status_updated", table_name="agentexecution")
    op.drop_index(op.f("ix_agentexecution_status"), table_name="agentexecution")
    op.drop_index(op.f("ix_agentexecution_postprocess_completed_at"), table_name="agentexecution")
    op.drop_index(op.f("ix_agentexecution_next_attempt_kind"), table_name="agentexecution")
    op.drop_index(op.f("ix_agentexecution_lease_expires_at"), table_name="agentexecution")
    op.drop_index(op.f("ix_agentexecution_latest_checkpoint_id"), table_name="agentexecution")
    op.drop_index("ix_agentexecution_invocation_status", table_name="agentexecution")
    op.drop_index(op.f("ix_agentexecution_invocation_id"), table_name="agentexecution")
    op.drop_index("ix_agentexecution_invocation_created", table_name="agentexecution")
    op.drop_index(op.f("ix_agentexecution_heartbeat_at"), table_name="agentexecution")
    op.drop_index(op.f("ix_agentexecution_first_token_at"), table_name="agentexecution")
    op.drop_index(op.f("ix_agentexecution_first_event_at"), table_name="agentexecution")
    op.drop_index(op.f("ix_agentexecution_current_attempt_id"), table_name="agentexecution")
    op.drop_index(op.f("ix_agentexecution_claimed_at"), table_name="agentexecution")
    op.drop_index(op.f("ix_agentexecution_cancel_requested_at"), table_name="agentexecution")
    op.drop_index(op.f("ix_agentexecution_agent_version_id"), table_name="agentexecution")
    op.drop_table("agentexecution")
    op.drop_index(
        "ux_memoryrecord_active_session",
        table_name="memoryrecord",
        postgresql_where=sa.text("session_id IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_index(
        "ux_memoryrecord_active_agent",
        table_name="memoryrecord",
        postgresql_where=sa.text("agent_id IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_memoryrecord_user_id"), table_name="memoryrecord")
    op.drop_index(op.f("ix_memoryrecord_source_type"), table_name="memoryrecord")
    op.drop_index(op.f("ix_memoryrecord_source_session_id"), table_name="memoryrecord")
    op.drop_index(op.f("ix_memoryrecord_source_message_id"), table_name="memoryrecord")
    op.drop_index(op.f("ix_memoryrecord_source_execution_id"), table_name="memoryrecord")
    op.drop_index(op.f("ix_memoryrecord_session_id"), table_name="memoryrecord")
    op.drop_index(op.f("ix_memoryrecord_memory_key"), table_name="memoryrecord")
    op.drop_index("ix_memoryrecord_lookup", table_name="memoryrecord")
    op.drop_index(op.f("ix_memoryrecord_last_accessed_at"), table_name="memoryrecord")
    op.drop_index(op.f("ix_memoryrecord_kind"), table_name="memoryrecord")
    op.drop_index(op.f("ix_memoryrecord_expires_at"), table_name="memoryrecord")
    op.drop_index(op.f("ix_memoryrecord_deleted_at"), table_name="memoryrecord")
    op.drop_index(op.f("ix_memoryrecord_agent_id"), table_name="memoryrecord")
    op.drop_table("memoryrecord")
    op.drop_index(op.f("ix_agentinvocation_user_id"), table_name="agentinvocation")
    op.drop_index("ix_agentinvocation_user_created", table_name="agentinvocation")
    op.drop_index(op.f("ix_agentinvocation_session_id"), table_name="agentinvocation")
    op.drop_index("ix_agentinvocation_session_created", table_name="agentinvocation")
    op.drop_index(op.f("ix_agentinvocation_agent_id"), table_name="agentinvocation")
    op.drop_table("agentinvocation")
    op.drop_index("ix_chatsession_user_updated", table_name="chatsession")
    op.drop_index(op.f("ix_chatsession_user_id"), table_name="chatsession")
    op.drop_index(op.f("ix_chatsession_langgraph_thread_id"), table_name="chatsession")
    op.drop_index(op.f("ix_chatsession_agent_version_id"), table_name="chatsession")
    op.drop_index("ix_chatsession_agent_updated", table_name="chatsession")
    op.drop_index(op.f("ix_chatsession_agent_id"), table_name="chatsession")
    op.drop_table("chatsession")
    op.drop_index(op.f("ix_agentversion_version"), table_name="agentversion")
    op.drop_index(op.f("ix_agentversion_agent_id"), table_name="agentversion")
    op.drop_index("ix_agentversion_agent_created", table_name="agentversion")
    op.drop_table("agentversion")
    op.drop_index("ix_useractiontoken_user_purpose", table_name="useractiontoken")
    op.drop_index(op.f("ix_useractiontoken_user_id"), table_name="useractiontoken")
    op.drop_index(op.f("ix_useractiontoken_used_at"), table_name="useractiontoken")
    op.drop_index(op.f("ix_useractiontoken_token_hash"), table_name="useractiontoken")
    op.drop_index(op.f("ix_useractiontoken_purpose"), table_name="useractiontoken")
    op.drop_index(op.f("ix_useractiontoken_expires_at"), table_name="useractiontoken")
    op.drop_table("useractiontoken")
    op.drop_index(op.f("ix_modelusage_user_id"), table_name="modelusage")
    op.drop_index("ix_modelusage_user_created", table_name="modelusage")
    op.drop_index(op.f("ix_modelusage_usage_available"), table_name="modelusage")
    op.drop_index(op.f("ix_modelusage_status"), table_name="modelusage")
    op.drop_index(op.f("ix_modelusage_session_id"), table_name="modelusage")
    op.drop_index(op.f("ix_modelusage_provider"), table_name="modelusage")
    op.drop_index(op.f("ix_modelusage_model_name"), table_name="modelusage")
    op.drop_index(op.f("ix_modelusage_latency_ms"), table_name="modelusage")
    op.drop_index(op.f("ix_modelusage_execution_id"), table_name="modelusage")
    op.drop_index("ix_modelusage_execution_category", table_name="modelusage")
    op.drop_index(op.f("ix_modelusage_created_at"), table_name="modelusage")
    op.drop_index(op.f("ix_modelusage_category"), table_name="modelusage")
    op.drop_index(op.f("ix_modelusage_call_id"), table_name="modelusage")
    op.drop_table("modelusage")
    op.drop_index(op.f("ix_authsession_user_id"), table_name="authsession")
    op.drop_index("ix_authsession_user_active", table_name="authsession")
    op.drop_index(op.f("ix_authsession_token_hash"), table_name="authsession")
    op.drop_index(op.f("ix_authsession_revoked_at"), table_name="authsession")
    op.drop_index(op.f("ix_authsession_expires_at"), table_name="authsession")
    op.drop_table("authsession")
    op.drop_index("ix_agentprofile_user_updated", table_name="agentprofile")
    op.drop_index(op.f("ix_agentprofile_user_id"), table_name="agentprofile")
    op.drop_index(op.f("ix_agentprofile_name"), table_name="agentprofile")
    op.drop_table("agentprofile")
    op.drop_index(op.f("ix_adminauditlog_target_user_id"), table_name="adminauditlog")
    op.drop_index("ix_adminauditlog_target_created", table_name="adminauditlog")
    op.drop_index(op.f("ix_adminauditlog_request_id"), table_name="adminauditlog")
    op.drop_index(op.f("ix_adminauditlog_created_at"), table_name="adminauditlog")
    op.drop_index(op.f("ix_adminauditlog_actor_user_id"), table_name="adminauditlog")
    op.drop_index("ix_adminauditlog_actor_created", table_name="adminauditlog")
    op.drop_index(op.f("ix_adminauditlog_action"), table_name="adminauditlog")
    op.drop_table("adminauditlog")
    op.drop_index(op.f("ix_appuser_status"), table_name="appuser")
    op.drop_index("ix_appuser_role_status", table_name="appuser")
    op.drop_index(op.f("ix_appuser_role"), table_name="appuser")
    op.drop_index(op.f("ix_appuser_locked_until"), table_name="appuser")
    op.drop_index(op.f("ix_appuser_last_login_at"), table_name="appuser")
    op.drop_index(op.f("ix_appuser_email_verified_at"), table_name="appuser")
    op.drop_index(op.f("ix_appuser_email_normalized"), table_name="appuser")
    op.drop_index(op.f("ix_appuser_created_at"), table_name="appuser")
    op.drop_table("appuser")
    for enum_name in (
        "toolexecutionstatus",
        "executionattemptstatus",
        "messagetype",
        "messagerole",
        "executionattemptkind",
        "runstatus",
        "memorysourcetype",
        "memorykind",
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS "{enum_name}"'))
    # ### end Alembic commands ###
